### ISSUE TITLE
c3eth.github.io - Content suggestions

### ISSUE THREAD

**Issue by stephen-rowan** [C3ETH/c3eth.github.io#15]
## c3eth.github.io - Content suggestions

Hi all, after experimenting with my own fork of docsy I would like to contribute some work to the ETH website and gather content suggestions via this Issue.

Running down the menu ..

### Main Page
- https://c3eth.github.io/
- At present this works as a landing page - it might be a good idea to highlight upcoming ETH here though.

### About Page
- https://c3eth.github.io/about/
- Meet the team - needs photos /bios added

### Catalyst
- https://c3eth.github.io/catalyst/
- This page is intended for ETH's interactions with Catalyst ?
- So details of ETH Fund 6 proposals should be added here ?

### Documentation
- https://c3eth.github.io/docs/
- Still in its generic state
- I suggest that this section documents - 
- 1) Communities  - the current reach of ETH - e.g. the communities (Vietnam, Japan, Indonesia etc ..)
- 2) Contribution - how to contribute to ETH (community and website)
- 3) Guides - how to use the website

### Blog
- https://c3eth.github.io/blog/
- The Blog could be used to document each ETH and possibly ETH meeting (in a summary digestible format that can be posted on social media etc.)
- Also news about ETH activities (proposals, Idea Fest etc).

### ETH Workflow
- Once we get started I guess a portion of ETH meetings will be devoted to discuss what content to upload ?

### Technical Clarifications
- the edit this page links of Docs and Blog open up the local copy of c3eth.github.io
- so editing content here and committing will trigger an action to rebuild the site 
- I had some issues with embedding images (whether to use shortcodes or just a link) in my docsy - would be good to agree up a standard way to embed Doc & Blog images

**Comment by YanTirta** [comment]
Awesome inputs @stephen-rowan ! Great structure, makes adding contribution easier, will try to contribute soon also. Still very much enjoying my first go at being CA. Somehow I'm enjoying it for some reason.

**Comment by wolstaeb** [comment]
@stephen-rowan please go ahead and modify or add any content you think is necessary. Just do a PR for any changes and I will check, merge, and set up the language translations as needed. The home page and about page are a little more involved to sort out so leave them to me. Unless you feel like diving into some HTML.

Editing a page: The site is built from the release branch so edits won't trigger a site rebuild. 

Your other questions: on workflow (yes), and images I will take a look at and get back to you.

### Pages

**Main Page** and **About Page**: Need work as per comment above.

**Documentation** & **Blog**: Please go ahead and update.

**Catalyst**: This is the main index page for Catalyst funds. So each fund will be added as they progress. Currently, the only fund6 ones are there. The body content of the index page needs to be written. Additional content needs to be drafted for the index pages too.

**Comment by elpidanang** [comment]
Great effort Robert
