### ISSUE TITLE
Funded Proposer Sub-Circle info for ETH website

### ISSUE THREAD

**Issue by VanCardui** [C3ETH/c3eth.github.io#169]
_Hi all - below is the text we'd like to be added to the ETH website (translated into as many languages as you have the capacity to do!), as discussed at the ETH planning meeting on 4th April.  (Of course, if people then respond via email in their first languages, we will need to come back to you about translations, and so we'll need to get an idea of translation costs from you.) Thanks so much for doing this!_

The **_Funded Proposers' Sub-Circle_** is a group of 7 people researching the problems faced by funded proposers in Catalyst.
If you are, or have been, a funded proposer in any funding round, we want to hear from you!  
🌟Is there anything about your experience that could be improved? 
🌟Is there anything you need more information about?
Please email your comments to 
**_funded-proposers@catalystcircle.io_**

**Comment by Mietran0407** [comment]
Already translated and posted on our Vietnamese community!

Nhóm Funded Proposers' Sub-Circle là một nhóm gồm 7 người đang nghiên cứu những vấn đề mà những người đề xuất dự án đã được tài trợ đã và đang gặp phải trong Catalyst. Những vấn đề của bạn sẽ được báo cáo lại với nhóm Catalyst Circle.

Nếu bạn đang, hoặc đã từng là người đề xuất được tài trợ trong bất kỳ quỹ tài trợ nào, chúng tôi muốn nghe ý kiến từ bạn!

🌟Có điều gì về trải nghiệm của bạn có thể được cải thiện không?
🌟Có điều gì bạn cần thêm thông tin không?

Vui lòng gửi email ý kiến của bạn tới
funded-proposer@catalystcircle.io

Trong trường hợp bạn không thể dùng tiếng Anh, bạn có thể nhắn thông tin qua @mietran0407 để hỗ trợ mọi người

**Comment by VanCardui** [comment]
Thanks so much Mie - but I have realised I made an error with the contact email address!

It should be funded-proposers@catalystcircle.io 
(that's "proposer**s**", plural)

Please could you change it? 
And I've changed it in my original post at the top of this thread, in case anyone else is going to do a translation and doesn't read all the way down here

**Comment by Mietran0407** [comment]
Thank you for your information, I have updated it and also updated it in the announcement to the Vietnamese community. it's all good now.
