### ISSUE TITLE
:page_facing_up: Update page/document for [content/fil/stakepool/_index.md]

### ISSUE THREAD

**Issue by PardusEidolon** [C3ETH/c3eth.github.io#187]
### Page Title

Filipino Stakepool _index.md Update

### Description of change

Update The linktitle for filipino stake pool index file.

### Is your suggestion and addition, or a change?

Change to exisitng page

### Which language does the change affect?

- [X] **English**
- [x] **Indonesian**
- [ ] **Japanese**
- [ ] **Korean**
- [ ] **Vietnamese**

### Which section of the website should the change be made?

Other

### Website URL

https://easterntownhall.com/stakepool/

### Source Document URL

https://github.com/C3ETH/c3eth.github.io/blob/main/content/fil/stakepool/_index.md

### Additional Information

Submit changes as a patch and any other changes that may be required.

### Wanting to help?

jack@yumi.ai

**Comment by andrecahyadi** [comment]
Hi, Jack @PardusEidolon. I've created the content for this page :)

**Comment by PardusEidolon** [comment]
Cool, I'll close this issue down then :-)
