### ISSUE TITLE
:page_facing_up: Add new page/document for Content Website Guide for ETH Github Wiki

### ISSUE THREAD

**Issue by PardusEidolon** [C3ETH/c3eth.github.io#198]
### Description of change

People need to effectively add content to the [Eastern townhall website](https://easterntownhall.com/). Currently, there are only 3 people who know how to do this. To keep content flowing, both inside contributors and outside need to know the website content pipeline created for this repository.

I will add a new page to the wiki with appropriate guidelines and workshop videos to help contributors get into the process quickly and smoothly. Written guides will also be added in the future.

### Is your suggestion and addition, or a change?

Add a new page

### Which language does the change affect?

- [X] **English**
- [ ] **Indonesian**
- [ ] **Japanese**
- [ ] **Korean**
- [ ] **Vietnamese**

### Which section of the website should the change be made?

Other

### Website URL

N/a

### Source Document URL

https://github.com/C3ETH/c3eth.github.io/wiki/Website-Content

### Wanting to help?

@PardusEidolon

**Comment by wolstaeb** [comment]
Here is the workshop video @PardusEidolon did. https://www.youtube.com/watch?v=nIEBMESoSRk
