### ISSUE TITLE
Content [Catalyst TV]: Add new section and pages for CatalystTV

### ISSUE THREAD

**Issue by wolstaeb** [C3ETH/c3eth.github.io#78]
### Page Title

CatalystTV

### Description of change

As part of our Fund 6 proposal, *Connecting Voters and Proposers* @Mietran0407 is doing a CatalystTV series or 5-minute interviews with Catalyst Proposers. These videos interviews will be transcribed, translated, and embedded into our website.

### Is your suggestion and addition, or a change?

Add a new page

### Which language does the change affect?

- [x] **English**
- [x] **Indonesian**
- [x] **Japanese**
- [x] **Korean**
- [x] **Vietnamese**

### Which section of the website should the change be made?

Other

### Source Document URL

https://easterntownhall.com/catalyst/fund6/eth-proposals/connect-asian-voters-proposers/

### Additional Information

See @Mietran0407 Catalyst Fund 7 Proposal [Cardano Catalyst TV](https://cardano.ideascale.com/a/dtd/Cardano-Catalyst-TV/381619-48088).

In our [Team metting](https://github.com/C3ETH/c3eth-operations/issues/96) @tienna asked for suggestions on how to promote Vietnam community proposals. As a first step, these would be a great start for the CatalystTV interviews. Also, @wolstaeb suggested reaching out to @cardanoz to cover the proposals on his Youtube Channel. 

### Wanting to help?

@wolstaeb

**Comment by YanTirta** [comment]
Will this be happening now @wolstaeb ? Or will it happen whether Catalyst TV receives funding or not? You did mention this is a part of our Fund 6 proposal which I assume we will be doing it now. If my assumption is correct, I would like to be part in the translation part of things. In terms of prepping translating video formats for **The Translation Pipeline**, reckon @andreassosilo might have the skillset to assist.

As you have mentioned in the proposal that houses **The Translation Pipeline**, and as I have consistently wanted to do, having a working demo would be really helpful for me to test the waters with potential clients. Although we have the examples done with our Eastern Town Hall Proposals in Fund 6, you mentioned that you wanted to pivot from the current tools being used. Would this pivot assumption be correct? And what would your general input be regarding this matter?

**Comment by Mietran0407** [comment]
Hi Yan! We can do it now by interviewing our submited proposal or Andreas's or your proposals! 

Here is my demo but it's really a basic one, please kindly advise if you think anything else should be improved. The point is to go straight to the main idea of the proposal and why it should be voted for. Should be from 3 - maximum 5 mins

https://youtu.be/MCr-nJ0W43s

**Comment by YanTirta** [comment]
Hello @mietran0407 ! Didn't notice you were here. Yes I would love this actually. I have a gut feeling @andreassosilo and the other Indonesian proposers would too, let me coordinate with them. This would be a good marketing tool besides the IdeaFest video.

If the Indonesian proposers share my sentiment, what time options would you be available to do this? I took a quick look at your demo and you did a great job Mie! Will look deeper into it before providing any feedbacks -if any-.

**Comment by PardusEidolon** [comment]
I've added in your catalyst tv section and a beginner page @Mietran0407. I will go over it in the tutorial for adding in content. feel free to translate it to vietnamese
